% Generated by Claude 3.7 Sonnet
% TODO: Check the paper Nakagawa(2013)
% Try a more comprehensive approach with variance decomposition
function r2 = calculate_nakagawa_r2(model)
    % Get fixed effects design matrix and coefficients
    X = designMatrix(model);
    beta = model.Coefficients.Estimate;
    
    % Calculate fixed effects variance
    var_fixed = var(X * beta);
    
    % Extract random effects variance (participant random intercept)
    var_random = sum(cell2mat(covarianceParameters(model)));
    
    % For Gamma with reciprocal link, approximate distribution-specific variance
    % Assuming dispersion parameter is available
    dispersion = model.Dispersion;
    link_function_adjustment = 1; % This may need adjustment for reciprocal link
    var_dist = dispersion * link_function_adjustment;
    
    % Calculate marginal and conditional R²
    r2_marginal = var_fixed / (var_fixed + var_random + var_dist);
    r2_conditional = (var_fixed + var_random) / (var_fixed + var_random + var_dist);
    
    r2 = struct('Marginal', r2_marginal, 'Conditional', r2_conditional);
end