% Generated by Claude 3.7 Sonnet
% TODO: Check the paper Nakagawa(2013)
% Try a more comprehensive approach with variance decomposition
function r2 = calculate_nakagawa_r2(glme_model)
    % Extract model components
    fixed_effects = glme_model.fixedEffects;
    % random_effects = glme_model.randomEffects;
    design_matrix = designMatrix(glme_model);
    % model_info = glme_model.modelInfo;
    % distribution = model_info.Distribution;
    % link_function = model_info.Link;
    
    
    % Calculate fixed effects variance
    var_fixed = var(design_matrix * fixed_effects);
    

    % Extract random effects variance (participant random intercept)
    var_random = sum(cell2mat(covarianceParameters(glme_model)));
    
    % For Gamma with reciprocal link, approximate distribution-specific variance
    % Assuming dispersion parameter is available
    shape_parameter = 1/glme_model.Dispersion; % Shape parameter is 1/dispersion in MATLAB
        
    % Get linear predictor
    linear_predictor = design_matrix * fixed_effects;
    fitted_values = 1 ./ linear_predictor;
    % Gamma variance is (mean^2)/shape
    var_dist = mean((fitted_values.^2) / shape_parameter);

    
    % Calculate marginal and conditional R²
    r2_marginal = var_fixed / (var_fixed + var_random + var_dist);
    r2_conditional = (var_fixed + var_random) / (var_fixed + var_random + var_dist);
    
    r2 = struct('Marginal', r2_marginal, 'Conditional', r2_conditional);
end