% generated by ChatGPT
function pre_lmm_pipeline(tbl, responseVar, fixedEffect, randomEffect)
    % pre_lmm_pipeline performs pre-tests before running a Linear Mixed Model.
    % USAGE:
    %   pre_lmm_pipeline(tbl, 'Response', 'Treatment', 'Subject')
    % INPUTS:
    %   tbl - Table containing the data
    %   responseVar - Name of the dependent variable (string)
    %   fixedEffect - Name of the fixed effect (string)
    %   randomEffect - Name of the random effect (string)
    
    %% 1. Check Normality of Residuals
    % Fit a Linear Mixed Model
    lme = fitglme(tbl, sprintf('%s ~ %s + (1|%s)', responseVar, fixedEffect, randomEffect), 'Distribution', 'InverseGaussian', 'Link', 'log');
    
    % Get residuals and perform Shapiro-Wilk test for normality
    residuals = lme.Residuals{:, 1};

    [h, pNormality] = lillietest(residuals);
    
    if pNormality < 0.05
        disp('Residuals are NOT normally distributed (p < 0.05). Consider transforming the data.');
    else
        disp('Residuals are normally distributed.');
    end
    
    %% 2. Check Homogeneity of Variance (Levene’s Test)
    [pLevene, ~] = vartestn(tbl.(responseVar), tbl.(fixedEffect), 'TestType', 'LeveneAbsolute');
    
    if pLevene < 0.05
        disp('Variances are NOT equal across groups (p < 0.05). Consider data transformation or using fitglme.');
    else
        disp('Homogeneity of variances assumption holds.');
    end
    
    %% 3. Check for Outliers
    disp('Visualizing potential outliers with a boxplot...');
    boxplot(tbl.(responseVar), tbl.(fixedEffect));
    
    %% 4. Check for Multicollinearity (Variance Inflation Factor)
    disp('Checking for multicollinearity between predictors...');
    X = dummyvar(categorical(tbl.(fixedEffect))); % Create dummy variables for the fixed effect
    VIF = diag(inv(corrcoef(X)))'; % Calculate Variance Inflation Factor
    disp('Variance Inflation Factors (VIF):');
    disp(VIF);
    
    % Check if VIF > 5, indicating multicollinearity
    if any(VIF > 5)
        disp('Warning: Multicollinearity detected! VIF > 5.');
    else
        disp('No significant multicollinearity detected.');
    end
    
    %% 5. Test if Random Effects are Needed (Likelihood Ratio Test)
    disp('Checking if random effects significantly improve the model...');
    
    % Fit model without random effects
    lme_no_random = fitglme(tbl, sprintf('%s ~ %s', responseVar, fixedEffect), 'Distribution', 'InverseGaussian', 'Link', 'log');
    
    % Compare models using likelihood ratio test
    siminfo = compare(lme_no_random, lme);
    if siminfo.pValue < 0.05
        disp('Random effects significantly improve the model (p < 0.05).');
    else
        disp('No significant improvement from random effects.');
    end
    
    %% Final Summary
    disp('Pre-tests completed. You can now proceed to fit the Linear Mixed Model (LMM).');
end