% Generated by claude sonnet 3.7 concise
function print_struct(input_struct, indent)
    % PRINT_STRUCT Prints a MATLAB struct in a readable format
    % Usage: print_struct(your_struct)
    %        print_struct(your_struct, initial_indent)
    
    if nargin < 2
        indent = 0;
    end
    
    field_names = fieldnames(input_struct);
    
    % Get maximum field name length for alignment
    max_name_length = 0;
    for i = 1:length(field_names)
        if length(field_names{i}) > max_name_length
            max_name_length = length(field_names{i});
        end
    end
    
    % Print each field
    for i = 1:length(field_names)
        field_name = field_names{i};
        field_value = input_struct.(field_name);
        
        % Create padding for alignment
        padding = repmat(' ', 1, max_name_length - length(field_name));
        
        % Create indentation
        indent_str = repmat('    ', 1, indent);
        
        % Handle different data types
        if isstruct(field_value)
            fprintf('%s%s%s: (struct)\n', indent_str, field_name, padding);
            print_struct(field_value, indent + 1);
        elseif iscell(field_value)
            fprintf('%s%s%s: (cell) {', indent_str, field_name, padding);
            if isempty(field_value)
                fprintf('}\n');
            else
                fprintf('\n');
                print_cell(field_value, indent + 1);
                fprintf('%s}\n', indent_str);
            end
        elseif ischar(field_value)
            fprintf('%s%s%s: "%s"\n', indent_str, field_name, padding, field_value);
        elseif isstring(field_value)
            fprintf('%s%s%s: "%s"\n', indent_str, field_name, padding, field_value);
        elseif islogical(field_value)
            if field_value
                fprintf('%s%s%s: true\n', indent_str, field_name, padding);
            else
                fprintf('%s%s%s: false\n', indent_str, field_name, padding);
            end
        elseif isnumeric(field_value)
            if numel(field_value) == 1
                if field_value == round(field_value)
                    fprintf('%s%s%s: %d\n', indent_str, field_name, padding, field_value);
                else
                    fprintf('%s%s%s: %g\n', indent_str, field_name, padding, field_value);
                end
            else
                fprintf('%s%s%s: [', indent_str, field_name, padding);
                if numel(field_value) <= 10
                    fprintf('%g ', field_value);
                    fprintf('\b]\n');
                else
                    fprintf('%d×%d %s]\n', size(field_value, 1), size(field_value, 2), class(field_value));
                end
            end
        else
            fprintf('%s%s%s: (%s)\n', indent_str, field_name, padding, class(field_value));
        end
    end
end

function print_cell(input_cell, indent)
    % Helper function to print cell arrays
    indent_str = repmat('    ', 1, indent);
    
    for i = 1:numel(input_cell)
        cell_value = input_cell{i};
        
        if isstruct(cell_value)
            fprintf('%s[%d] (struct)\n', indent_str, i);
            print_struct(cell_value, indent + 1);
        elseif iscell(cell_value)
            fprintf('%s[%d] (cell) {\n', indent_str, i);
            print_cell(cell_value, indent + 1);
            fprintf('%s}\n', indent_str);
        elseif ischar(cell_value)
            fprintf('%s[%d] "%s"\n', indent_str, i, cell_value);
        elseif islogical(cell_value)
            if cell_value
                fprintf('%s[%d] true\n', indent_str, i);
            else
                fprintf('%s[%d] false\n', indent_str, i);
            end
        elseif isnumeric(cell_value)
            if numel(cell_value) == 1
                if cell_value == round(cell_value)
                    fprintf('%s[%d] %d\n', indent_str, i, cell_value);
                else
                    fprintf('%s[%d] %g\n', indent_str, i, cell_value);
                end
            else
                fprintf('%s[%d] [', indent_str, i);
                if numel(cell_value) <= 10
                    fprintf('%g ', cell_value);
                    fprintf('\b]\n');
                else
                    fprintf('%d×%d %s]\n', size(cell_value, 1), size(cell_value, 2), class(cell_value));
                end
            end
        else
            fprintf('%s[%d] (%s)\n', indent_str, i, class(cell_value));
        end
    end
end