% generated by ChatGPT
function run_llm(tbl, responseVar, fixedEffect, randomEffect)
    % RUNLMM Fits a linear mixed model and performs post hoc tests.
    % USAGE:
    %   runLMM(tbl, 'Response', 'Treatment', 'Subject')
    % INPUTS:
    %   tbl - Table containing the data
    %   responseVar - Name of the dependent variable (string)
    %   fixedEffect - Name of the fixed effect (string)
    %   randomEffect - Name of the random effect (string)
    
    % Ensure categorical variables
    tbl.(fixedEffect) = categorical(tbl.(fixedEffect));
    tbl.(randomEffect) = categorical(tbl.(randomEffect));

    % Define the model formula
    formula = sprintf('%s ~ %s + (1|%s)', responseVar, fixedEffect, randomEffect);
    
    % Fit the Linear Mixed Model (LMM)
    lme = fitlme(tbl, formula);
    
    % Display model summary
    disp('Linear Mixed Model Summary:')
    disp(lme)
    
    % Perform ANOVA on LMM
    disp('ANOVA Results:')
    anovaResults = anova(lme);
    disp(anovaResults)

    % Check if the fixed effect is significant (p < 0.05)
    pMainEffect = anovaResults.pValue(2); % p-value of the fixed effect
    if pMainEffect < 0.05
        disp('Significant effect detected! Running post hoc tests...')
        
        % Perform pairwise post hoc comparisons (Tukey-Kramer correction)
        results = multcompare(lme, fixedEffect, 'CType', 'tukey-kramer');
        
        % Display results
        disp('Post Hoc Pairwise Comparisons:')
        disp(results)
    else
        disp('No significant main effect found. Post hoc tests skipped.')
    end
end
